name: Push and Deploy to S3
on:
  push:
    branches:
    - 'main'
    - 'dev'
    
env: 
  NODE_VER: 20.15.0
    
jobs:
  snyk-scan:
    name: Snyk Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@b98d498629f1c368650224d6d212bf7dfa89e4bf
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
                --severity-threshold=medium
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ 'ubuntu-latest' }}
    needs: ['snyk-scan']
    permissions:
      security-events: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - language: javascript
            build-mode: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
          
  test:
    environment: production
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setting up NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VER }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install

    - name: Test
      run: echo "It has no tests"
      
  build-and-push:
    environment: production
    runs-on: ubuntu-22.04
    needs: ['test']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setting up NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VER }}
        cache: 'npm'
      
    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build
      run: npm install && npm run build
      env:
        REACT_APP_BASE_URL: ${{ vars.REACT_APP_BASE_URL }}
        NODE_ENV: ${{ vars.NODE_ENV }}

    - name: Push to S3 Bucket
      run: aws s3 cp ./build/ s3://frontend-bucket-internship/ --recursive 
        
