name: Push and Deploy to S3
on:
  push:
    branches:
    - 'main'
    - 'dev'
    
env: 
  NODE_VER: 20.15.0
    
jobs:
  test:
    environment: production
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setting up NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VER }}
        
    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm run test
      
  build-and-push:
    environment: production
    runs-on: ubuntu-22.04
    needs: ['test']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setting up NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VER }}
      
    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build
      run: npm run build

    - name: Push to S3 Bucket
      run: aws s3 cp /build/* s3://frontend-bucket-internship/ --recursive 
        
